language: ruby
sudo: false
rvm:
  - 1.9.3

install:
  - nvm install 6.9
  - nvm use 6.9
  - npm install

addons:
  apt:
    packages:
    - aspell-en
cache: bundler
before_script: npm run lint
script: bundle exec rspec spec && bundle exec middleman build --verbose
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/continuous-delivery.sh"
  on:
    branch: master
env:
  global:
    secure: KVhVKajiNcZiuc3QOLBhyVD/nk4+TRVXIJpJ/eBL8kbEIhSb+rxDUij9T7+R5YVAW8L8pyq7vx6jXnKK/B9s+YOyD7XtgRHz50va+stgrVbsA6sdqpuuqWFm03KN54JnhpiZ4dRFtd4nI4I/awaVJyk+EkNNfAFdR4BEdV0eL1o=
